name: Release
on:
  push:
    branches:
      - master
      - next
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install pnpm
        run: curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node
      - name: Install Root Dependencies
        run: pnpm install --filter vime
      - name: Install Packages dependencies
        run: pnpm install --filter ./packages
      - name: Run Tests
        run: pnpm run test:ci --filter @vime/core
      - name: Build Coverage Report
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: cd packages/core && pnpx codecov
      - name: Build Packages
        run: pnpm run build --filter vime
      - name: Release Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm run release --filter vime
