name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install pnpm
        run: curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: pnpm run build --filter @vime/core
      - name: Test
        run: pnpm run test:ci --filter @vime/core
      - name: Coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: cd packages/core && pnpx codecov
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm run release --filter @vime/core